#!/bin/bash

# Abort immediately 
set -e

if [ "$1" = "-h" ]; then
	exec /usr/local/s2i/usage
fi

HOME_DIR=/opt/app
HOME_SOURCE_DIR=$HOME_DIR/src

echo "--> Building Spring Boot application from source"
echo "---> Running Maven3"
echo "---> MVN_ARGS = $MVN_ARGS"

cd $HOME_SOURCE_DIR
mvn clean install $MVN_ARGS

# Copy artefact generated to home folder
cp $HOME_SOURCE_DIR/target/*.jar $HOME_DIR

# Clean up src folder, maven dependencies, installation
rm -r $HOME_SOURCE_DIR