#!/bin/bash

# Abort immediately
set -e

if [ "$1" = "-h" ]; then
	exec /usr/local/s2i/usage
fi

LOCAL_BINARY_DIR=/opt/app/bin
LOCAL_SOURCE_DIR=/opt/app/src

echo "--> Building Spring Boot application from source"
echo "---> Running Maven"
echo "---> MVN_ARGS = $MVN_ARGS"

cd /opt/app/src
mvn clean install $MVN_ARGS

# Copy artefact
cp $LOCAL_SOURCE_DIR/target/*.jar $LOCAL_BINARY_DIR

# Clean up src folder
rm -r $LOCAL_SOURCE_DIR
