#!/bin/bash

# Abort immediately
set -e

if [ "$1" = "-h" ]; then
	exec /usr/local/s2i/usage
fi

LOCAL_SOURCE_DIR=/opt/app/src

echo "--> Building Spring Boot application from source"
echo "---> Running Maven"
echo "---> MVN_ARGS = $MVN_ARGS"

cd /opt/app/src
mvn clean install $MVN_ARGS

# Clean up after maven
mvn clean
if [ -d "$LOCAL_SOURCE_DIR/.m2/repository" ]; then
	rm -r "$LOCAL_SOURCE_DIR/.m2/repository"
fi